-- DropForeignKey
ALTER TABLE "Ots" DROP CONSTRAINT "Ots_ottId_fkey";

-- AlterTable
ALTER TABLE "Ots" ALTER COLUMN "OT" DROP NOT NULL,
ALTER COLUMN "ottId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Ots" ADD CONSTRAINT "Ots_ottId_fkey" FOREIGN KEY ("ottId") REFERENCES "OT"("OTmaximo") ON DELETE SET NULL ON UPDATE CASCADE;
